version: "2"

linters:
  enable:
    - bodyclose
    - errorlint
    - gocritic
    - gosec
    - nilerr
    - nolintlint
    - revive
    - rowserrcheck
    - sqlclosecheck
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - revive
        text: unused-parameter

formatters:
  enable:
    - gofmt
    - goimports
